
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 14 23:39:08 EDT 2011
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class TokenIds {
  /* terminals */
  public static final int DIVIDE = 14;
  public static final int LPAREN = 26;
  public static final int SEMI = 30;
  public static final int MINUS = 12;
  public static final int INSTANCEOF = 10;
  public static final int RPAREN = 27;
  public static final int NOT = 16;
  public static final int AND = 17;
  public static final int LT = 21;
  public static final int OR = 18;
  public static final int COMMA = 31;
  public static final int CLASS = 3;
  public static final int GEQ = 24;
  public static final int PLUS = 11;
  public static final int ASSIGN = 25;
  public static final int IF = 5;
  public static final int DOT = 32;
  public static final int ID = 33;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int INT_CONST = 34;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int LEX_ERROR = 2;
  public static final int TIMES = 13;
  public static final int LBRACE = 28;
  public static final int ELSE = 6;
  public static final int WHILE = 7;
  public static final int RBRACE = 29;
  public static final int MODULUS = 15;
  public static final int EXTENDS = 4;
  public static final int NE = 20;
  public static final int LEQ = 22;
  public static final int BOOLEAN_CONST = 35;
  public static final int STRING_CONST = 36;
  public static final int GT = 23;
}

